### ISSUE TITLE
node_id_mismatch test is flaky

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#2388] opened 2024-12-06 08:51 UTC
See https://github.com/restatedev/restate/actions/runs/12195103656/job/34020095131?pr=2335#step:11:601

**Comment by tillrohrmann** [comment] 2024-12-06 08:53
Seems to be a duplicate of https://github.com/restatedev/restate/issues/2160.

**Closed by tillrohrmann** 2024-12-06 08:53 UTC
Labels: bug
