### ISSUE TITLE
Creating a delayed invocation from an external client

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#1272] opened 2024-03-06 18:05 UTC
A user asked on [Discord](https://discord.com/channels/1128210118216007792/1214635273141616761) whether it is possible to create a delayed invocation from an external client. At the moment, it is possible to invoke a service without awaiting its response but it is not possible to specify a delay for this invocation. Maybe this is something we can support with the new ingress/API rework.

**Comment by tillrohrmann** [comment] 2024-03-06 18:05
fyi @igalshilman and @slinkydeveloper

**Comment by slinkydeveloper** [comment] 2024-03-06 19:13
Duplicate of #1235

**Closed by slinkydeveloper** 2024-03-06 19:13 UTC
Labels: ingress
